# Generated by Django 3.2.7 on 2021-09-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopokemon',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
